twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']

    globals:
        ga_enabled: '%env(GA_ENABLED)%'
        ga_code: '%env(GA_CODE)%'
        supported_locales: '%supported_locales%'
