# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    storage_dir: '%kernel.project_dir%/public/storage'
    app_storage_dir: '%kernel.project_dir%/storage'
    admin_email: '%env(ADMIN_EMAIL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Services\Music\Yandex\BaseClient:
        arguments:
            $login: '%env(YANDEX_LOGIN)%'
            $password: '%env(YANDEX_PASSWORD)%'
            $cookieDir: '%kernel.project_dir%/storage/yandex'
            $proxy: '%env(YANDEX_PROXY)%'

    YandexCommonClient:
        class: App\Services\Music\Yandex\BaseClient
        arguments:
            $login: '%env(YANDEX_COMMON_LOGIN)%'
            $password: '%env(YANDEX_COMMON_PASSWORD)%'
            $cookieDir: '%kernel.project_dir%/storage/yandex'
            $proxy: '%env(YANDEX_COMMON_PROXY)%'

    YandexPremiumClient:
        class: App\Services\Music\Yandex\BaseClient
        arguments:
            $login: '%env(YANDEX_LOGIN)%'
            $password: '%env(YANDEX_PASSWORD)%'
            $cookieDir: '%kernel.project_dir%/storage/yandex'
            $proxy: '%env(YANDEX_PROXY)%'

    App\Services\Music\Yandex\Yandex:
        arguments:
            $downloader: '@YandexPremiumClient'
            $parser: '@YandexCommonClient'

    App\Event\Dispatcher\EventDispatcher:
        class: App\Event\Dispatcher\MessengerEventDispatcher

